org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

addon_id=bluemap-laserio
addon_name=BlueMap LaserIO Add-on
addon_version=0.1.0-alpha.2
addon_group=io.github.jan-guenter
artifact_id=bluemap-laserio-addon
bluemap_version=5.22-agent.backport-5.22-mc1.21.1-2

accepted_jar_size=111676
accepted_jar_sha256=d01eb100dd57f7efc1ac4ce8c004e02320901e83ef16337dac24b9e690849828
accepted_sources_jar_size=74565
accepted_sources_jar_sha256=654a8ab0bfc0ea38b65a638e1f459acef3891e41ddf2607916c9f6468a860429
accepted_pom_size=1317
accepted_pom_sha256=1d0598c7ac8cd13e015f58f343a355fc1691dc638310b40320d1e8ce52737f21
accepted_module_size=2819
accepted_module_sha256=7961b5578b6e4ea22fe2c06827916a6bd104ea9018e3a2b985d7c13a0684d84e
