org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

addon_id=bluemap-laserio
addon_name=BlueMap LaserIO Add-on
addon_version=0.1.0-alpha.4
addon_group=io.github.jan-guenter
artifact_id=bluemap-laserio-addon
bluemap_version=5.22-feature.backport-5.23-stateless-java-web-server-46

accepted_jar_size=116935
accepted_jar_sha256=d719f59197505f00acce4ef6ab72fab7fc62f766369e8035f7c7e8bff2d19793
accepted_sources_jar_size=79841
accepted_sources_jar_sha256=6d8766fe2e31cfc72b1de07cddb6f5ea9642f3d149a8c71939bd72ab653877b3
accepted_pom_size=1317
accepted_pom_sha256=4e98439a19531071503ab479443fdac51d8cf22a71f20136c6a7cf62ff0b3306
accepted_module_size=2819
accepted_module_sha256=a9685470576d50fa78d65882f668b41ec6c00766f8eda08df1e9b9a0b3584d50
