org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

addon_id=bluemap-laserio
addon_name=BlueMap LaserIO Add-on
addon_version=0.1.0-alpha.1
addon_group=io.github.jan-guenter
artifact_id=bluemap-laserio-addon
bluemap_version=5.22-agent.backport-5.22-mc1.21.1-2

accepted_jar_size=110887
accepted_jar_sha256=006900dd9000c6614c60b38df46b6cd1940dab53f059a381c282e9d79e89dbf1
accepted_sources_jar_size=73956
accepted_sources_jar_sha256=f4dc9e678e3730c6f54f1e0bd81bd1ef3424e227e8bd7a73c7ad59e947878aee
accepted_pom_size=1317
accepted_pom_sha256=2d74e77f8c4d1bc2369c363d05c75bc421eee0b2f0567227dea500d66d115bab
accepted_module_size=2819
accepted_module_sha256=ca08ac2e7cc605c1ae135319e645dc916f371d9712243c2794fb608826f5e5bf
