#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate the bounded deterministic LaserIO staging gallery."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys

import cases


ROOT = Path(__file__).resolve().parent


def text_bytes(value: str) -> bytes:
    return (value.rstrip() + "\n").encode("utf-8")


def json_bytes(value: object) -> bytes:
    return text_bytes(json.dumps(value, indent=2, sort_keys=True))


def placements_tsv() -> bytes:
    lines = [
        "cell\tsection\tlabel\tx\ty\tz\tblock_state\tlaser_color_argb\t"
        "connections\trendered_connections\tpartner\tblock_entity_nbt\t"
        "expected"
    ]
    lines.extend(
        "\t".join(
            (
                placement.cell,
                placement.section,
                placement.label,
                str(placement.x),
                str(placement.y),
                str(placement.z),
                placement.block_state,
                f"0x{placement.laser_color:08x}",
                ",".join(
                    f"{offset.x}/{offset.y}/{offset.z}"
                    for offset in placement.connections
                ) or "-",
                ",".join(
                    f"{offset.x}/{offset.y}/{offset.z}"
                    for offset in placement.rendered_connections
                ) or "-",
                (
                    f"{cases.DIMENSION}@{placement.partner.x}/"
                    f"{placement.partner.y}/{placement.partner.z}"
                    if placement.partner is not None else "-"
                ),
                placement.nbt,
                placement.expected,
            )
        )
        for placement in cases.PLACEMENTS
    )
    return text_bytes("\n".join(lines))


def clear_function() -> bytes:
    envelope = cases.ENVELOPE
    return text_bytes(
        "# Generated by gallery/generate.py; do not edit.\n"
        f"schedule clear {cases.NAMESPACE}:verify_20t\n"
        f"fill {envelope['min_x']} {envelope['min_y']} "
        f"{envelope['min_z']} {envelope['max_x']} {envelope['max_y']} "
        f"{envelope['max_z']} minecraft:air"
    )


def build_function() -> bytes:
    lines = [
        "# Generated by gallery/generate.py; do not edit.",
        f"scoreboard objectives add {cases.OBJECTIVE} dummy",
        f"scoreboard players add #builds {cases.OBJECTIVE} 1",
        f"function {cases.NAMESPACE}:clear",
        "forceload add " + " ".join(str(value) for value in cases.FORCELOAD),
        "fill " + " ".join(str(value) for value in cases.PAD)
        + " minecraft:smooth_stone",
    ]
    for placement in cases.PLACEMENTS:
        lines.extend(
            (
                f"# {placement.cell}: {placement.label}",
                f"setblock {placement.x} {placement.y} {placement.z} "
                f"{placement.block_state}{placement.nbt}",
            )
        )
    lines.extend(
        (
            f"function {cases.NAMESPACE}:verify_immediate",
            f"schedule function {cases.NAMESPACE}:verify_20t 20t replace",
        )
    )
    return text_bytes("\n".join(lines))


def failure_check(condition: str) -> str:
    return (
        f"execute unless {condition} run scoreboard players add "
        f"#failures {cases.OBJECTIVE} 1"
    )


def verify_function() -> bytes:
    lines = [
        "# Generated by gallery/generate.py; do not edit.",
        f"scoreboard players set #failures {cases.OBJECTIVE} 0",
        f"scoreboard players set #checked {cases.OBJECTIVE} 0",
    ]
    for placement in cases.PLACEMENTS:
        lines.extend(
            (
                f"# {placement.cell}: {placement.label}",
                failure_check(
                    f"block {placement.x} {placement.y} {placement.z} "
                    f"{placement.block_state}"
                ),
                f"scoreboard players add #checked {cases.OBJECTIVE} 1",
                failure_check(
                    f"data block {placement.x} {placement.y} {placement.z} "
                    f"{placement.nbt}"
                ),
                f"scoreboard players add #checked {cases.OBJECTIVE} 1",
            )
        )
    lines.extend(
        (
            f"execute unless score #builds {cases.OBJECTIVE} matches 1 run "
            f"scoreboard players add #failures {cases.OBJECTIVE} 1",
            f"scoreboard players add #checked {cases.OBJECTIVE} 1",
        )
    )
    return text_bytes("\n".join(lines))


def phase_function(phase: str) -> bytes:
    payload = [
        {"text": f"LaserIO gallery {phase}: "},
        {"score": {"name": f"#{phase}_checked", "objective": cases.OBJECTIVE}},
        {"text": " checks, "},
        {
            "score": {
                "name": f"#{phase}_failures",
                "objective": cases.OBJECTIVE,
            }
        },
        {"text": " failures"},
    ]
    return text_bytes(
        "# Generated by gallery/generate.py; do not edit.\n"
        f"function {cases.NAMESPACE}:verify\n"
        f"scoreboard players operation #{phase}_failures {cases.OBJECTIVE} = "
        f"#failures {cases.OBJECTIVE}\n"
        f"scoreboard players operation #{phase}_checked {cases.OBJECTIVE} = "
        f"#checked {cases.OBJECTIVE}\n"
        "tellraw @a " + json.dumps(payload, separators=(",", ":"))
    )


def base_files() -> dict[Path, bytes]:
    function_root = Path(f"datapack/data/{cases.NAMESPACE}/function")
    return {
        Path("placements.tsv"): placements_tsv(),
        Path("datapack/pack.mcmeta"): json_bytes(
            {
                "pack": {
                    "description": (
                        "ATM 1.2.0 LaserIO synthetic BlueMap gallery; "
                        "not natural-fixture proof"
                    ),
                    "pack_format": 48,
                }
            }
        ),
        Path("datapack/data/minecraft/tags/function/load.json"): json_bytes(
            {"values": [f"{cases.NAMESPACE}:load"]}
        ),
        function_root / "load.mcfunction": text_bytes(
            "# Generated by gallery/generate.py; do not edit.\n"
            f"scoreboard objectives add {cases.OBJECTIVE} dummy\n"
            "tellraw @a {\"text\":\"LaserIO gallery loaded; "
            f"run /function {cases.NAMESPACE}:build\",\"color\":\"yellow\"}}"
        ),
        function_root / "clear.mcfunction": clear_function(),
        function_root / "build.mcfunction": build_function(),
        function_root / "verify.mcfunction": verify_function(),
        function_root / "verify_immediate.mcfunction": phase_function(
            "immediate"
        ),
        function_root / "verify_20t.mcfunction": phase_function("20t"),
        function_root / "release.mcfunction": text_bytes(
            "# Generated by gallery/generate.py; do not edit.\n"
            f"schedule clear {cases.NAMESPACE}:verify_20t\n"
            "forceload remove "
            + " ".join(str(value) for value in cases.FORCELOAD)
        ),
    }


def generated_files() -> dict[Path, bytes]:
    files = base_files()
    checksum = "".join(
        f"{hashlib.sha256(payload).hexdigest()}  {path.as_posix()}\n"
        for path, payload in sorted(files.items(), key=lambda row: row[0].as_posix())
    )
    files[Path("SHA256SUMS")] = checksum.encode("ascii")
    return files


def write_or_check(check: bool) -> int:
    failures: list[str] = []
    files = generated_files()
    for relative, payload in files.items():
        destination = ROOT / relative
        if check:
            if not destination.is_file() or destination.read_bytes() != payload:
                failures.append(relative.as_posix())
        else:
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_bytes(payload)
    if failures:
        print(f"generated gallery differs: {', '.join(failures)}", file=sys.stderr)
        return 1
    action = "checked" if check else "wrote"
    print(f"{action} {len(files)} deterministic gallery files")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    return write_or_check(args.check)


if __name__ == "__main__":
    raise SystemExit(main())
