# Generated by gallery/generate.py; do not edit.
scoreboard objectives add laserio_glr dummy
scoreboard players add #builds laserio_glr 1
function laserio_gallery:clear
forceload add 160 160 191 191
fill 160 99 160 184 99 189 minecraft:smooth_stone
# A1: default laser node
setblock 164 100 164 laserio:laser_node{connections:[],renderedConnections:[],myWorldPos:{X:164,Y:100,Z:164},laserColor:1425997824,wrenchAlpha:0}
# A2: default basic connector facing down
setblock 170 100 164 laserio:laser_connector[facing=down]{connections:[],renderedConnections:[],myWorldPos:{X:170,Y:100,Z:164},laserColor:1425997824,wrenchAlpha:0}
# A3: default advanced connector facing down
setblock 176 100 164 laserio:laser_connector_advanced[facing=down]{connections:[],renderedConnections:[],myWorldPos:{X:176,Y:100,Z:164},laserColor:1425997824,wrenchAlpha:0}
# B1: cyan laser node
setblock 164 100 171 laserio:laser_node{connections:[],renderedConnections:[],myWorldPos:{X:164,Y:100,Z:171},laserColor:1409338623,wrenchAlpha:0}
# B2: green basic connector facing east
setblock 170 100 171 laserio:laser_connector[facing=east]{connections:[],renderedConnections:[],myWorldPos:{X:170,Y:100,Z:171},laserColor:1414922069,wrenchAlpha:0}
# B3: violet advanced connector facing south
setblock 176 100 171 laserio:laser_connector_advanced[facing=south]{connections:[],renderedConnections:[],myWorldPos:{X:176,Y:100,Z:171},laserColor:1422677503,wrenchAlpha:0}
# C1: node link renderer
setblock 164 100 178 laserio:laser_node{connections:[{pos:{X:4,Y:0,Z:0}}],renderedConnections:[{pos:{X:4,Y:0,Z:0}}],myWorldPos:{X:164,Y:100,Z:178},laserColor:1426041378,wrenchAlpha:0}
# C2: node link target
setblock 168 100 178 laserio:laser_node{connections:[{pos:{X:-4,Y:0,Z:0}}],renderedConnections:[],myWorldPos:{X:168,Y:100,Z:178},laserColor:1426041378,wrenchAlpha:0}
# D1: basic connector diagonal-link renderer
setblock 176 100 178 laserio:laser_connector[facing=east]{connections:[{pos:{X:4,Y:0,Z:3}}],renderedConnections:[{pos:{X:4,Y:0,Z:3}}],myWorldPos:{X:176,Y:100,Z:178},laserColor:1411566830,wrenchAlpha:0}
# D2: advanced connector diagonal-link target
setblock 180 100 181 laserio:laser_connector_advanced[facing=west]{connections:[{pos:{X:-4,Y:0,Z:-3}}],renderedConnections:[],myWorldPos:{X:180,Y:100,Z:181},laserColor:1411566830,wrenchAlpha:0}
# E1: advanced partner west port
setblock 164 100 186 laserio:laser_connector_advanced[facing=east]{connections:[],renderedConnections:[],myWorldPos:{X:164,Y:100,Z:186},laserColor:1424901290,wrenchAlpha:0,partnerDimPos:{dimension:"minecraft:overworld",blockpos:{X:171,Y:100,Z:186}}}
# E2: advanced partner east port
setblock 171 100 186 laserio:laser_connector_advanced[facing=west]{connections:[],renderedConnections:[],myWorldPos:{X:171,Y:100,Z:186},laserColor:1424901290,wrenchAlpha:0,partnerDimPos:{dimension:"minecraft:overworld",blockpos:{X:164,Y:100,Z:186}}}
function laserio_gallery:verify_immediate
schedule function laserio_gallery:verify_20t 20t replace
