# Generated by gallery/generate.py; do not edit.
function laserio_gallery:verify
scoreboard players operation #20t_failures laserio_glr = #failures laserio_glr
scoreboard players operation #20t_checked laserio_glr = #checked laserio_glr
tellraw @a [{"text":"LaserIO gallery 20t: "},{"score":{"name":"#20t_checked","objective":"laserio_glr"}},{"text":" checks, "},{"score":{"name":"#20t_failures","objective":"laserio_glr"}},{"text":" failures"}]
