# Generated by gallery/generate.py; do not edit.
scoreboard players set #failures laserio_glr 0
scoreboard players set #checked laserio_glr 0
# A1: default laser node
execute unless block 164 100 164 laserio:laser_node run scoreboard players add #failures laserio_glr 1
scoreboard players add #checked laserio_glr 1
execute unless data block 164 100 164 {connections:[],renderedConnections:[],myWorldPos:{X:164,Y:100,Z:164},laserColor:1425997824,wrenchAlpha:0} run scoreboard players add #failures laserio_glr 1
scoreboard players add #checked laserio_glr 1
# A2: default basic connector facing down
execute unless block 170 100 164 laserio:laser_connector[facing=down] run scoreboard players add #failures laserio_glr 1
scoreboard players add #checked laserio_glr 1
execute unless data block 170 100 164 {connections:[],renderedConnections:[],myWorldPos:{X:170,Y:100,Z:164},laserColor:1425997824,wrenchAlpha:0} run scoreboard players add #failures laserio_glr 1
scoreboard players add #checked laserio_glr 1
# A3: default advanced connector facing down
execute unless block 176 100 164 laserio:laser_connector_advanced[facing=down] run scoreboard players add #failures laserio_glr 1
scoreboard players add #checked laserio_glr 1
execute unless data block 176 100 164 {connections:[],renderedConnections:[],myWorldPos:{X:176,Y:100,Z:164},laserColor:1425997824,wrenchAlpha:0} run scoreboard players add #failures laserio_glr 1
scoreboard players add #checked laserio_glr 1
# B1: cyan laser node
execute unless block 164 100 171 laserio:laser_node run scoreboard players add #failures laserio_glr 1
scoreboard players add #checked laserio_glr 1
execute unless data block 164 100 171 {connections:[],renderedConnections:[],myWorldPos:{X:164,Y:100,Z:171},laserColor:1409338623,wrenchAlpha:0} run scoreboard players add #failures laserio_glr 1
scoreboard players add #checked laserio_glr 1
# B2: green basic connector facing east
execute unless block 170 100 171 laserio:laser_connector[facing=east] run scoreboard players add #failures laserio_glr 1
scoreboard players add #checked laserio_glr 1
execute unless data block 170 100 171 {connections:[],renderedConnections:[],myWorldPos:{X:170,Y:100,Z:171},laserColor:1414922069,wrenchAlpha:0} run scoreboard players add #failures laserio_glr 1
scoreboard players add #checked laserio_glr 1
# B3: violet advanced connector facing south
execute unless block 176 100 171 laserio:laser_connector_advanced[facing=south] run scoreboard players add #failures laserio_glr 1
scoreboard players add #checked laserio_glr 1
execute unless data block 176 100 171 {connections:[],renderedConnections:[],myWorldPos:{X:176,Y:100,Z:171},laserColor:1422677503,wrenchAlpha:0} run scoreboard players add #failures laserio_glr 1
scoreboard players add #checked laserio_glr 1
# C1: node link renderer
execute unless block 164 100 178 laserio:laser_node run scoreboard players add #failures laserio_glr 1
scoreboard players add #checked laserio_glr 1
execute unless data block 164 100 178 {connections:[{pos:{X:4,Y:0,Z:0}}],renderedConnections:[{pos:{X:4,Y:0,Z:0}}],myWorldPos:{X:164,Y:100,Z:178},laserColor:1426041378,wrenchAlpha:0} run scoreboard players add #failures laserio_glr 1
scoreboard players add #checked laserio_glr 1
# C2: node link target
execute unless block 168 100 178 laserio:laser_node run scoreboard players add #failures laserio_glr 1
scoreboard players add #checked laserio_glr 1
execute unless data block 168 100 178 {connections:[{pos:{X:-4,Y:0,Z:0}}],renderedConnections:[],myWorldPos:{X:168,Y:100,Z:178},laserColor:1426041378,wrenchAlpha:0} run scoreboard players add #failures laserio_glr 1
scoreboard players add #checked laserio_glr 1
# D1: basic connector diagonal-link renderer
execute unless block 176 100 178 laserio:laser_connector[facing=east] run scoreboard players add #failures laserio_glr 1
scoreboard players add #checked laserio_glr 1
execute unless data block 176 100 178 {connections:[{pos:{X:4,Y:0,Z:3}}],renderedConnections:[{pos:{X:4,Y:0,Z:3}}],myWorldPos:{X:176,Y:100,Z:178},laserColor:1411566830,wrenchAlpha:0} run scoreboard players add #failures laserio_glr 1
scoreboard players add #checked laserio_glr 1
# D2: advanced connector diagonal-link target
execute unless block 180 100 181 laserio:laser_connector_advanced[facing=west] run scoreboard players add #failures laserio_glr 1
scoreboard players add #checked laserio_glr 1
execute unless data block 180 100 181 {connections:[{pos:{X:-4,Y:0,Z:-3}}],renderedConnections:[],myWorldPos:{X:180,Y:100,Z:181},laserColor:1411566830,wrenchAlpha:0} run scoreboard players add #failures laserio_glr 1
scoreboard players add #checked laserio_glr 1
# E1: advanced partner west port
execute unless block 164 100 186 laserio:laser_connector_advanced[facing=east] run scoreboard players add #failures laserio_glr 1
scoreboard players add #checked laserio_glr 1
execute unless data block 164 100 186 {connections:[],renderedConnections:[],myWorldPos:{X:164,Y:100,Z:186},laserColor:1424901290,wrenchAlpha:0,partnerDimPos:{dimension:"minecraft:overworld",blockpos:{X:171,Y:100,Z:186}}} run scoreboard players add #failures laserio_glr 1
scoreboard players add #checked laserio_glr 1
# E2: advanced partner east port
execute unless block 171 100 186 laserio:laser_connector_advanced[facing=west] run scoreboard players add #failures laserio_glr 1
scoreboard players add #checked laserio_glr 1
execute unless data block 171 100 186 {connections:[],renderedConnections:[],myWorldPos:{X:171,Y:100,Z:186},laserColor:1424901290,wrenchAlpha:0,partnerDimPos:{dimension:"minecraft:overworld",blockpos:{X:164,Y:100,Z:186}}} run scoreboard players add #failures laserio_glr 1
scoreboard players add #checked laserio_glr 1
execute unless score #builds laserio_glr matches 1 run scoreboard players add #failures laserio_glr 1
scoreboard players add #checked laserio_glr 1
