# Generated by gallery/generate.py; do not edit.
function laserio_gallery:verify
scoreboard players operation #immediate_failures laserio_glr = #failures laserio_glr
scoreboard players operation #immediate_checked laserio_glr = #checked laserio_glr
tellraw @a [{"text":"LaserIO gallery immediate: "},{"score":{"name":"#immediate_checked","objective":"laserio_glr"}},{"text":" checks, "},{"score":{"name":"#immediate_failures","objective":"laserio_glr"}},{"text":" failures"}]
